404 page not found added
axioned/codex pull request #33
Opened 2023-06-14 12:11 UTC by saifaliaxioned

2023-06-16 14:11 UTC, zishanaxioned commented on src/pages/snippets/[slug].astro
> +const { status } = Astro.response;
You can remove this.

2023-06-16 14:11 UTC, zishanaxioned requested changes
Remove the code for redirection and check again

2023-06-19 06:52 UTC, banuragaxioned requested changes

2023-06-19 06:52 UTC, banuragaxioned commented on tailwind.config.cjs
> +      montserrat: ["Montserrat"],
don't need this to be added for just one page (404)

2023-06-20 08:57 UTC, banuragaxioned approved these changes

2023-06-20 08:58 UTC, merged