Dev
axioned/codex pull request #6
Opened 2022-09-21 14:07 UTC by dshirlyaxioned

2022-10-03 13:08 UTC, banuragaxioned commented
- overflow hidden / inner scroll needed for side nav bar (col 1)
- on smaller/mobile - only main content with the hamburger toggle should be visible
- on smaller/mobile - hamburger toggle should show the col 1 and 2 (over the full viewport), and partial main content (as you have done already)
- Use col 1 layout like Gmail (see image)
<img width="69" alt="CleanShot 2022-10-03 at 18 36 39@2x" src="https://user-images.githubusercontent.com/26105313/193584028-e4c8714a-6544-49a1-b768-8ab376b20daa.png">

2022-10-11 13:41 UTC, banuragaxioned requested changes

2022-10-11 13:41 UTC, banuragaxioned commented on components/SideNav.js
> +      <ul className="bg-gray-200 pt-4">
![image](https://user-images.githubusercontent.com/26105313/195105335-0d1150e5-808a-461e-9d79-90ef80fb25af.png)
Let's remove the padding at the top.

The selected stage also has some space on the left of the selected item 
![image](https://user-images.githubusercontent.com/26105313/195105549-fa9e8f99-3937-4ac9-8893-2ea5a2607043.png)

2022-10-11 13:53 UTC, dshirlyaxioned commented on components/PrimaryNav.js
> +    <div
based on viewport width the layout will change.
currently in dev mode we have to refresh but for an user it will show based on their screen viewport

2022-10-11 14:35 UTC, banuragaxioned commented on components/PrimaryNav.js
> +    <div
Not sure I understand. Could you direct me to something in the documentation that suggests this? It might make it easier for me to understand what you already know ;)

2022-10-12 06:54 UTC, banuragaxioned commented on components/PrimaryNav.js
> +    <div
Cool, thanks! Curious - what was the change/edit that worked here?

2022-10-19 21:04 UTC, banuragaxioned requested changes
Nice work on the layout. We are almost there. Some (hopefully) tiny changes. We can work on the animations later on - though it was good to see some of them already being there ;)

2022-10-19 21:04 UTC, banuragaxioned commented on assets/icons/Icon1.jsx
> +export const Icon1 = () => (
Are we better off using something like https://heroicons.com/? Creating and maintaining this file might get difficult after a point. Can you do that please? Thanks!

2022-10-19 21:04 UTC, banuragaxioned commented on components/SideNav.js
> +} from "../assets/icons/Icon1";
Added comment on the `assets/icons/Icon1.jsx` file.

2022-10-19 21:04 UTC, banuragaxioned commented on next.config.js
> +module.exports = {
I suspect we won't need to add this here and in our direct package dependencies if we are using something like Heroicons. If so, let's revert this.

2022-10-19 21:04 UTC, banuragaxioned commented on package.json
> +    "@svgr/webpack": "^6.5.0",
I suspect we won't need to add this here and in our direct package dependencies if we are using something like Heroicons. If so, let's revert this.

2022-10-20 08:33 UTC, banuragaxioned approved these changes

2022-10-20 08:33 UTC, merged